### ISSUE TITLE
Sync percentage is wrong 

### ISSUE THREAD

**Issue by Skirmant** [ZcashFoundation/zec-qt-wallet#86] opened 2018-12-31 17:05 UTC
The percentage of synchronized blocks is different when running zec-qt-wallet (0.5.5) and zcashd (2.0.2) on the same datadir. The issue remains when --no-embedded is used as well.

![screenshot_2018-12-31_18-56-37](https://user-images.githubusercontent.com/4085181/50564603-d84b9700-0d2e-11e9-8357-4af497d71ec5.png)
![screenshot_2018-12-31_19-03-15](https://user-images.githubusercontent.com/4085181/50564606-db468780-0d2e-11e9-8124-8e64a05069d9.png)

**Comment by adityapk00** [comment] 2018-12-31 18:08
This is interesting. I think you might have 2 zcashd running. Is there a zcashd tab in zec-qt-wallet? That’s the embedded zcashd which is running inside zec-qt-wallet which might be in a different sync state than external zcashd.

**Comment by adityapk00** [comment] 2018-12-31 18:10
Oh, wait. You already tried —no-embedded, so that’s not the case. Very strange. 

Does  the problem remain if you right click on the green check on the bottom right and click refresh?

**Comment by adityapk00** [comment] 2018-12-31 18:13
Oh, I think I know what the problem is. zec-qt-wallet is showing the verification percentage while zcashd is showing the block download percentage. Verification is slightly lagging block download on your machine, so the percentages are different. 

Thanks for reporting this. I’ll fix it.

**Comment by adityapk00** [comment] 2019-01-02 20:03
Fixed in v0.5.6

**Closed by adityapk00** 2019-01-02 20:03 UTC
