### ISSUE TITLE
Unable to specify a decimal number for sending

### ISSUE THREAD

**Issue by DurinDwarf** [ZcashFoundation/zec-qt-wallet#69] opened 2018-12-07 04:07 UTC
Hello,
In version 0.5.0 for Windows, impossible to specify a decimal number in the «amount» field. Keypress «.» doesn't work...
To take over this issue I had to check «Max available» checkbox to get the «.»

However, if I press «,» that works, but it's a separator for thousands, not for decimals...

**Comment by adityapk00** [comment] 2019-01-02 18:49
Closing this since I can't repro anywhere, and it might be fixed because of the new Qt version. Please reopen if you're still seeing this with the latest zec-qt-wallet.

**Comment by sandakersmann** [comment] 2019-02-09 19:40
I have this bug on v0.5.9 on Ubuntu 18.04.1 LTS. Please reopen.

**Comment by adityapk00** [comment] 2019-02-09 21:21
Thanks for the update. Can you confirm your country/locale please

**Comment by sandakersmann** [comment] 2019-02-09 21:34
![screenshot from 2019-02-09 22-33-32](https://user-images.githubusercontent.com/6118832/52526571-e809b400-2cba-11e9-910b-08baa76d65bf.png)

**Comment by adityapk00** [comment] 2019-02-19 23:04
Duplicate of #103

**Closed by adityapk00** 2019-02-19 23:04 UTC
