### ISSUE TITLE
'Import private key' does nothing

### ISSUE THREAD

**Issue by buzon7** [ZcashFoundation/zec-qt-wallet#109] opened 2019-02-20 14:39 UTC
I tried with 't' and 'zs', a wallet.dat from backup and a freshly generated one. I see nothing happening after I paste the info - no new addresses appear in the balances. So make sure to backup your wallet.dat. HD does work - I managed to generate the same new address as before and using --rescan to restore coins on it.

**Comment by adityapk00** [comment] 2019-02-20 14:45
Did you try with the latest version 0.5.10? This might be a duplicate of #102 

Basically, the import takes a long time, since it has to scan the entire blockchain, and the dialog wasn’t being shown at the start, giving the impression that nothing is happening. It was fixed in yesterday’s release.

**Comment by buzon7** [comment] 2019-02-20 15:16
Ah, ok, sorry. I was following a websockets version. When will you guys merge them? ))

**Comment by adityapk00** [comment] 2019-02-20 15:23
Oh, right. I will merge websockets into main branch this week. We’ll have he public release of the android app this Friday, most likely.

**Comment by buzon7** [comment] 2019-02-20 15:55
Fantastic stuff! Could you also add an option to lauch zqw without graphic UI? I would love to run both zcashd and zec-qt-wallet on a headless linux server... And we need Address book to sync into the App )))

**Comment by adityapk00** [comment] 2019-02-20 19:10
Closing this issue, we'll track the android address book on the android github

**Closed by adityapk00** 2019-02-20 19:10 UTC
